name: Full CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ Checkout SCM
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2ï¸âƒ£ Setup Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
          cache: maven

      # 3ï¸âƒ£ Build JAR
      - name: Build JAR
        working-directory: backend
        run: mvn clean package -DskipTests
      - name: Check built files
        run: ls -l backend/target

      # 4ï¸âƒ£ Prepare EC2 directories
      - name: Prepare EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/ec2-user/app
            mkdir -p /var/log/app
            chmod -R 755 /home/ec2-user
            chmod -R 755 /var/log/app
            echo "EC2 ready"

      # 5ï¸âƒ£ Upload JAR
      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: backend/target/*.jar
          target: /home/ec2-user/app/
          overwrite: true

      # 6ï¸âƒ£ Start Application (NO KILL)
      - name: Start Application
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/app

            nohup env \
            MYSQL_HOST=database-1.c43qqq2mgy2s.us-east-1.rds.amazonaws.com \
            MYSQL_PORT=3306 \
            MYSQL_USERNAME=admin \
            MYSQL_PASSWORD=mahima123 \
            java -jar datastore-0.0.7.jar \
            --server.port=8084 \
            > /var/log/app/datastore.log 2>&1 &

            sleep 5
            echo "Running process:"
            ps -ef | grep datastore | grep -v grep || true
            echo "ðŸš€ Application started"
